### ISSUE TITLE
App fail on Migration to Firestore

### ISSUE THREAD

**Issue by danielkellyio** [JimSadler/vue_forum#1]
Hey Jim, 
I figured I'd move the convo here to be less noisy in the comments. :) 

I've pulled the repo, installed the deps, and run it locally and strangely enough I am able to successfully [see a thread page](http://localhost:8080/thread/-KvgjI6bfbWYlbYV5ndr).
![Screen Shot 2022-01-07 at 9 47 43 AM](https://user-images.githubusercontent.com/7635209/148569179-524564c5-6744-4e88-881d-d6f90475a10a.png)

And this is connected to your Firestore, so I'm really at a loss as to what the issue could be. I know that doesn't make things less frustrating :) 

Perhaps, to make sure it's not some kind of npm package corruption, could you delete the node_modules directory and freshly install deps with 
```
npm install
```

**Comment by danielkellyio** [comment]
also just thinking of other things that might be different between our 2 machines...
I'm running Node 16.13.0

Could use [nvm](https://github.com/nvm-sh/nvm) to switch between node versions if yours is different

**Comment by JimSadler** [comment]
yea this is weird. I have deleted node_modules and then reinstalled. no change.
![Screen Shot 2022-01-07 at 6 17 39 PM](https://user-images.githubusercontent.com/17620727/148619360-fc2cede5-e470-4416-a5df-48437e4178d2.png)
 

I am using node version v15.14.0

**Comment by JimSadler** [comment]
I just  changed to node 16.13.0, rebuilt node_modules, and no change.

**Comment by JimSadler** [comment]
the vueDevTools does not show all the component
![Screen Shot 2022-01-07 at 6 26 11 PM](https://user-images.githubusercontent.com/17620727/148619953-2bd4ed05-5303-4209-a29d-f75dfeb98721.png)
s

**Comment by danielkellyio** [comment]
that last screenshot is of the home page. At the end of the lesson "Migrating Vuex to use Cloud Firestore Database" we have not yet fetched any of the data for the home page, only the thread show page.

What happens when you visit a particular thread like this one? 
http://localhost:8080/thread/-KvgjI6bfbWYlbYV5ndr

**Comment by JimSadler** [comment]
ahh. now I am getting it.  thanks.

**Comment by danielkellyio** [comment]
Great! Happy to help :)
